# openapi.yaml
# ---
# 人間にもAIにも分かりやすいように、各フィールドの「意図」をコメントで記述
# ---
components:
  schemas:
    GenerateHowaRequest:
      type: object
      required: [theme, audiences]
      properties:
        theme:
          type: string
          description: "法話の中心となるテーマや感情"
          example: "感謝"
        audiences:
          type: array
          description: "この法話を届けたい人々の層"
          items:
            type: string
            enum: [子供, 若者, ビジネスパーソン, 高齢者, 指定なし]
          example: ["若者"]

    HowaResponse:
      type: object
      properties:
        title:
          type: string
          description: "生成された法話の顔となるタイトル"
        introduction:
          type: string
          description: "聴衆の心を引き込む、物語の始まり（時事ネタを含む）"
        problem_statement:
          type: string
          description: "導入から仏教のテーマへと繋ぐ、問題提起"
        sutra_quote:
          type: object
          description: "法話の根拠となる、経典からの引用"
          properties:
            text:
              type: string
              description: "引用された経典の本文"
            source:
              type: string
              description: "出典（例: 法句経 第十七章『忿怒品』）"
        modern_example:
          type: string
          description: "教えを現代のシーンで解説する、具体的な例え話"
        conclusion:
          type: string
          description: "聴衆が持ち帰れる、物語の締めくくりと実践のヒント"
